main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', 
        views.home, name="home"),
    path('about/', 
        views.about, name="about"),
    # trips:
    path('trips/', 
        views.trips_index, name="index"),
    path('trips/<int:trip_id>', 
        views.trips_detail, name="detail"),
    path('trips/create/', 
        views.TripCreate.as_view(), name="trips_create"),
    path('trips/<int:pk>/update', 
        views.TripUpdate.as_view(), name='trips_update'),
    path('trips/<int:pk>/delete', 
        views.TripDelete.as_view(), name='trips_delete'),
    # stops:
    path('trips/<int:trip_id>/stop_create/',
        views.stop_create, name="stop_create"),
    path('stops/<int:stop_id>',
        views.stop_detail, name="stop_detail"),
    path('stops/<int:pk>/update',
        views.StopUpdate.as_view(), name='stop_update'),
    path('stops/<int:pk>/delete',
        views.StopDelete.as_view(), name='stop_delete'),
    path('stops/<int:stop_id>/add_photo/', 
        views.add_photo, name='add_photo'),
    #auth
    path('accounts/signup/',
        views.signup, name='signup'),



    # auth:
    # path('accounts/signup/', views.signup, name='signup'),
]

tripster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Trip(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    start_location = models.CharField(max_length=100)
    end_location = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'trip_id': self.id})


class Stop(models.Model):
    stop_name = models.CharField(max_length=100)
    stop_adress = models.CharField(max_length=100)
    stop_city = models.CharField(max_length=100)
    stop_state = models.CharField(max_length=100)
    stop_date = models.DateField()
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('stop_detail', kwargs={'stop_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for stop_id: {self.stop_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Stop


class StopForm(ModelForm):
    class Meta:
        model = Stop
        fields = ['stop_name', 'stop_adress',
                  'stop_city', 'stop_state', 'stop_date']

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Trip, Stop, Photo
from .forms import StopForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import boto3
import uuid


# Constants:
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'tripster-fg'


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

# trips:


@login_required
def trips_index(request):
    trips = Trip.objects.filter(user=request.user)
    return render(request, 'trips/index.html', {'trips': trips})


@login_required
def trips_detail(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    stop_form = StopForm()
    stops = Stop.objects.all()

    # ACCESSKEY = 'pk.eyJ1IjoiYmVuZ2xhc3NlciIsImEiOiJja3JvOWJkeG8yODNtMndwZXB5cGYwYTZiIn0.t5K6aF-sboGpQD_xI_tU4w'

    # startCoordinates = requests.get(
    #     f'https://api.mapbox.com/geocoding/v5/mapbox.places/{trip.start_location}.json?access_token={ACCESSKEY}').json()

    # endCoordinates = f'https://api.mapbox.com/geocoding/v5/mapbox.places/{trip.end_location}.json?access_token={ACCESSKEY}'

    return render(request, 'trips/detail.html', {
        'trip': trip,
        'stop_form': stop_form,
        'stops': stops,
        # 'startCoordinates': startCoordinates
    })


class TripCreate(LoginRequiredMixin, CreateView):
    model = Trip
    fields = ['name', 'start_date', 'end_date',
              'start_location', 'end_location']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TripUpdate(LoginRequiredMixin, UpdateView):
    model = Trip
    fields = ['name', 'start_date', 'end_date',
              'start_location', 'end_location']


class TripDelete(LoginRequiredMixin, DeleteView):
    model = Trip
    success_url = '/trips/'

# stops:


@login_required
def stop_create(request, trip_id):
    form = StopForm(request.POST)
    if form.is_valid():
        new_stop = form.save(commit=False)
        new_stop.trip_id = trip_id
        new_stop.save()
    return redirect('detail', trip_id=trip_id)


@login_required
def stop_detail(request, stop_id):
    stop = Stop.objects.get(id=stop_id)

    return render(request, 'stops/detail.html', {
        'stop': stop,
    })


class StopUpdate(LoginRequiredMixin, UpdateView):
    model = Stop
    fields = ['stop_name', 'stop_adress',
              'stop_city', 'stop_state', 'stop_date']


class StopDelete(LoginRequiredMixin, DeleteView):
    model = Stop
    success_url = '/trips/'


# auth:

def logout(request):
    return render(request, 'logout.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid Signup - Please Try Again'

    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error_message': error_message})

# Photo:


@login_required
def add_photo(request, stop_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, stop_id=stop_id)
            photo.save()
        except Exception as error:
            print('An error occured uploading file to S3')
            print(error)
    return redirect('stop_detail', stop_id=stop_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

        <h1>About Tripster</h1>

        <p id="about-tripster">
            If you love to travel and are eager to plan your next road trip, 
            you have come to the right place! At Tripster we believe travel 
            is essential to a happy life. We are here to help guide you as 
            you embark on your next journey. We provide the best user experience 
            for you to easily plan your destinations, add photos from each place 
            you visit, and more. Enjoy panning your next big get away and always
            travel safe!
        </p>

    <div class="about-page-img" />
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- maps cdn -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    
    <!--  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Chivo:300,700|Playfair+Display:700i" rel="stylesheet">
    <title>Tripster</title>
</head>
<body>
    <header class="navbar-fixed">
        <nav class="transparent z-depth-0">
            <div class="nav-wrapper">
                <ul>
                    <li>
                            <a href="{% url 'home' %}" class="left brand-logo">Tripster</a>   
                    </li>
                </ul>
                <ul class="right">
                    <li>
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'index' %}">View All Trips</a>
                    </li>
                    <li>
                        <a href="{% url 'trips_create' %}">Create a Trip</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content%}
        {% endblock %}
    </main>
    <footer class="page-footer transparent z-depth-0">
        <div class="right"> All Rights Reserved, &copy; 2021 Tripster</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="home-page">
        <h1>Welcome to Tripster</h1>
        <h5>The best place to help you get away</h5>
        <a class="btn" href="{% url 'trips_create' %}">Create Trip</a>
    </div>

    <div class="home-page-img" />

{% endblock %}

main_app/templates/main_app/stop_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Stop:</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn" type="submit" value="Yes - Delete!">
    <a class="btn red" href="{% url 'stop_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/stop_form.html
{% extends 'base.html' %}
{% block content %}

    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>


<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn" type="submit" value="Submit">
</form>


<script>
  
    const stopDateEl = document.getElementById('id_stop_date');

    M.Datepicker.init(stopDateEl, {
        format: 'yyyy-mm-dd',
        default: new Date(),
        setDefault: true,
        autoClose: true,
    });

</script>

{% endblock %}

main_app/templates/main_app/trip_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Trip:</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn" type="submit" value="Yes - Delete!">
    <a href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/trip_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Create Trip:</h1>

{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn" type="submit" value="Submit">
</form>

<div class="create-trips-page-img" />
<script>
    //Constants:
    const startDateEl = document.getElementById('id_start_date');
    const endDateEl = document.getElementById('id_end_date');

    //Configure the datepicker
    M.Datepicker.init(startDateEl, {
        format: 'yyyy-mm-dd',
        default: new Date(),
        setDefault: true,
        autoClose: true,
    });
    M.Datepicker.init(endDateEl, {
        format: 'yyyy-mm-dd',
        default: new Date(),
        setDefault: true,
        autoClose: true,
    });

</script>

{% endblock %}

main_app/templates/stops/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="centered">
    <h1>{{stop.stop_name}} Details</h1>
    <h3>{{stop.stop_adress}}</h3>
    <h3>{{stop.stop_city}}, {{stop.stop_state}}</h3>
    <h3>on {{stop.stop_date}}</h3>
</div>

<div class="card-action centered">
    <a class='btn' href="{% url 'stop_update' stop.id %}">Edit</a>
    <a class='btn red' href="{% url 'stop_delete' stop.id %}">Delete</a>
</div>

<hr>
{% for photo in stop.photo_set.all %}
    <img src="{{photo.url}}" alt="{{stop.name}}" class="responsive-img card-panel">
{% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}
<form class="card-panel" action="{% url 'add_photo' stop.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br>
    <br>
    <input type="submit" class="btn" value="Upload Photo">
</form>
<div class="stops-page-img" />

{% endblock %}

main_app/templates/trips/detail.html
{% extends 'base.html' %}

{% block content%}
<h1 class="centered">{{ trip.start_location }}</h1>
<div class="row">
    <div class="col s6">
        <h4>Your Trip Details</h4>
        <!-- Trip Start Card -->
        <div class="card">
            <a href="/trips/{{trip.id}}">
                <div class="card-content">
                    <p>Starting at: <span class="bold">{{trip.start_location}}</span> on <span
                            class="bold">{{trip.start_date}}</span></p>
                </div>
            </a>
        </div>

        <!-- STOP CARDS -->

        {% for s in trip.stop_set.all %}
        <div class="card">
            <a href="{% url 'stop_detail' s.id %}">
                <div class="card-content">
                    <p><span class="bold">{{s.stop_name}}</span> on <span class="bold">{{s.stop_date}}</span></p>
                </div>
            </a>
        </div>
        {% endfor %}


        <!-- Trip End Card -->
        <div class="card">
            <a href="/trips/{{trip.id}}">
                <div class="card-content">
                    <p>Ending at: <span class="bold">{{trip.end_location}}</span> on <span
                            class="bold">{{trip.end_date}}</span></p>
                </div>
            </a>
        </div>



        <div class="card-action">
            <a class='btn' href="{% url 'trips_update' trip.id %}">Edit</a>
            <a class='btn red' href="{% url 'trips_delete' trip.id %}">Delete</a>
        </div>
    </div>




    <!-- Adding a stop -->
    <div class="col s6">


        <h4>Add A Stop</h4>
        <form action="{% url 'stop_create' trip.id %}" method="post">
            {% csrf_token %}
            {{ stop_form.as_p }}
            <input type="submit" class="btn" value="Add Stop">
        </form>
    </div>
</div>
<!-- <p id="startCoordinate">{{ startCoordinates.features.0.center}}</p> -->
<!-- MAP -->
<hr />

<div id='map' style='width: 69vw; height: 40vh;'></div>

<div class="trips-page-img" />
<!-- datepicker script -->
<script>
    const stopDateEl = document.getElementById('id_stop_date');

    M.Datepicker.init(stopDateEl, {
        format: 'yyyy-mm-dd',
        default: new Date(),
        setDefault: true,
        autoClose: true,
    });

    mapboxgl.accessToken =
        'pk.eyJ1IjoiYmVuZ2xhc3NlciIsImEiOiJja3JvOWJkeG8yODNtMndwZXB5cGYwYTZiIn0.t5K6aF-sboGpQD_xI_tU4w';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-100.03, 38.91],
        zoom: 2
    });

    var marker = new mapboxgl.Marker() 
        .setLngLat([-100.03, 38.91]) 
        .addTo(map); 

    var geocoder = new MapboxGeocoder({ // Initialize the geocoder
        accessToken: mapboxgl.accessToken, // Set the access token
        mapboxgl: mapboxgl, // Set the mapbox-gl instance
        marker: false, // Do not use the default marker style
    });

    // Add the geocoder to the map
    map.addControl(geocoder);

    
</script>


{% endblock%}

main_app/templates/trips/index.html
{% extends 'base.html' %}

{% block content%}
    <h1>All Trips:</h1>
    {% for trip in trips %}
        <div class="card">
            <a href="/trips/{{trip.id}}">
                <div class="card-content">
                    <span class="card-title">{{ trip.name }}</span>
                    <p>Dates: {{trip.start_date}} - {{trip.end_date}}</p>
                    <p>From: {{trip.start_location}} - {{trip.end_location}}</p>
                </div>
            </a>
        </div>
    {% endfor %}

    <div class="trips-page-img" />
{% endblock%}